### ISSUE TITLE
Emulator

### ISSUE THREAD

**Issue by kpfaulkner** [Azure/azure-documentdb-dotnet#169] opened 2016-11-17 02:11 UTC
Can't get the SDK 1.9.* to work properly with the DocDB emulator. I cant get any version working except 1.0.0...

Specifically CreateDatabaseAsync hangs then crashes with:

{System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

Although the emulator is running on port 8081 (and the connection URL has 8081 specified), somehow its trying against 443...   and BOOM...

Is port 443 hardcoded somewhere in the client lib source?

Ken

**Comment by kpfaulkner** [comment] 2016-11-17 02:39
Turns out this is due to EnableEndpointDiscovery being true. Setting to false fixes it.

**Comment by arramac** [comment] 2016-11-17 05:03
@kpfaulkner thanks for reporting the issue (and posting the workaround). We'll confirm the root cause and patch the emulator/SDK asap.

**Comment by arramac** [comment] 2016-11-18 02:09
Root cause is understood (port mapping for region-endpoints). We will release a new version of the emulator. 

Meanwhile, please start with /port=443 or use EnableEndpointDiscovery = false when connecting.

**Comment by arramac** [comment] 2016-11-29 19:26
This is now fixed in the latest drop of the emulator.

**Closed** 2016-11-29 19:26 UTC
