### ISSUE TITLE
Problems querying using CamelCasePropertyNamesContractResolver

### ISSUE THREAD

**Issue by cannehag** [Azure/azure-documentdb-dotnet#122] opened 2016-05-04 09:02 UTC
I would like to use a general CamelCasePropertyNamesContractResolver for Json.NET.
This works well for serialization/deserialization but not when querying on properties using LINQ since that seems to require the JsonPropertyAttribute.

**Comment by aliuy** [comment] 2016-06-14 00:54
This appears to be a duplicate of https://github.com/Azure/azure-documentdb-dotnet/issues/55

**Closed by aliuy** 2016-06-14 00:54 UTC
