### ISSUE TITLE
HashPartitionResolver gives different results when hosted in a 32 or 64-bits process

### ISSUE THREAD

**Issue by clementpuell** [Azure/azure-documentdb-dotnet#200] opened 2017-01-30 17:16 UTC
When hosted in a 32-bit or a 64-bit process (eg IIS Express), the DocumentDB client returns different values for `HashPartitionResolver.ResolveForRead`.
We consider this a bug as we expect the DocumentDB database to be independent of the underlying architecture of our client apps and hosting servers (local debugging, On-Premise server, Azure Web App, etc.).

- 32-bit process, finds the second of two collections:
```
Environment.Is64BitProcess; // false
_partitionResolver.ResolveForRead("CFR201601192F81OGO"); // dbs/T6t8AA==/colls/T6t8ANdyZQE=/
```
- 64-bit process, finds the first of two collections:
```
Environment.Is64BitProcess; // true
_partitionResolver.ResolveForRead("CFR201601192F81OGO"); // dbs/T6t8AA==/colls/T6t8ALDFcwA=/
```

SDK client version used: 1.11.3.

**Comment by mingaliu** [comment] 2017-01-30 18:56
Thanks for the report. We will look into it.
In the same time,  HashPartitionResolver is for client side partitioning and is deprecated. We currently support the server side automatic partitioning (Partitioned Collection), can you move to Partitioned Collection?

**Comment by rnagpal** [comment] 2017-02-02 07:20
@clementpuell This was a known issue and the reason why we couldn't fix this after we knew about it as it would be a breaking change now for existing applications relying on the new hash value that is platform independent. As Ming mentioned, client side partitioning is marked as deprecated as you would have noticed in the documentation. Please use the server side partitioning feature now. That way you will not have to maintain different collections in your app. Server side partitioning is based on architecture independent hash based partitioning. Let us know if that would be fine for your case.

**Comment by clementpuell** [comment] 2017-02-07 14:38
Thanks for the answers.

Yes I noticed that client-side partitioning is deprecated but server-side partitioning is also much more expensive (due to a minimum of 10 000 RU/s per partition). We will just work our way around this bug for now.
Do you confirm that client-side partitioning won't be maintained? Will the feature be removed in a future version?

**Comment by rnagpal** [comment] 2017-02-07 14:55
@clementpuell We would be soon releasing the support for lower RUs for partitioned collections which will make it down from 10,100 to 2,600. Please email askdocdb at microsoft dot com if you are interested in it. Also, you mentioned that current minimum is 10,000 per partition. Just wanted to clarify that its 10,000 for the whole collection(which internally includes many partitions), so per partition RUs will be much lower(10,000 equally divided for all partitions).

Yes, I can confirm that client-side partitioning will not be maintained but we are keeping it for backward compatibility and we may remove it in a next major version bump, so I'd not take a dependency on it.

Also, server-side partitioning is the way to go since you don't have to manage the collections yourself and it's automatically take care for you as your data grows.

**Closed** 2017-02-11 15:56 UTC
