### ISSUE TITLE
Could not load file or assembly 'System.Diagnostics.DiagnosticSource' when using Microsoft.Azure.Graphs NuGet package

### ISSUE THREAD

**Issue by amusse** [Azure/azure-documentdb-dotnet#383] opened 2017-11-16 19:07 UTC
I've been having numerous "Could not load file or assembly" issues when using the Microsoft.Azure.Graphs 0.3.1-preview nuget package in my projects. One example is when trying to connect to the Azure DocumentDB Graph API but I get a System.AggregateException:

```
System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at GraphDbRepro.GraphDb..ctor(String databaseId, String collectionId, String endpointUrl, String authKey) in D:\projects\GraphDbRepro\GraphDbRepro\GraphDb.cs:line 29
   at GraphDbRepro.Client.Program.Main(String[] args) in D:\projects\GraphDbRepro\GraphDbRepro.Client\Program.cs:line 16

Inner Exception 1:
AggregateException: One or more errors occurred.

Inner Exception 2:
FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

```

I am using VS 2017 Version 15.3.3 and using the 0.3.1-preview Microsoft.Azure.Graphs nuget package. I have a .NET Core Class Library project targeting .NET Framework 4.6.1 that creates a connection to the graph API and has methods that perform various gremlin queries. I also have a .NET Core Console App targeting .NET Framework 4.6.1 that references that Class Library and actually tries to execute some gremlin queries. I have attached a basic repro case representing this setup. 

[GraphDbRepro.zip](https://github.com/Azure/azure-documentdb-dotnet/files/1479853/GraphDbRepro.zip)

**Comment by olivertowers** [comment] 2017-12-20 22:49
According to this github issue, [#487](https://github.com/aspnet/JavaScriptServices/issues/487 ),  the issue is issue caused by `System.Net.Http 4.3.0` package which is either part of .NET SDK version or one of the dependencies of Microsoft.Azure.Graphs depends on.

Using your repro projects, I was able to fix the issue by explicitly referencing package `System.Net.Http` >= v4.3.1 in GraphDBRepo.csproj.

Also, I recommend you use this [sample project](https://github.com/Azure-Samples/azure-cosmos-db-graph-dotnet-getting-started/blob/master/GraphGetStarted/GraphGetStarted.csproj) as a template for your .net core/std projects which need to reference Microsoft.Azure.Graphs. There are a few other dependency issues that may crop up and the sample project should include all known workarounds.

**Comment by olivertowers** [comment] 2018-01-18 04:58
Closing issue since a workaround has been provided and the issue is not specific to Microsoft.Azure.Graphs.

**Closed by olivertowers** 2018-01-18 04:58 UTC
Labels: graph
