### ISSUE TITLE
Handling Unique Constraint Conflicts

### ISSUE THREAD

**Issue by m1nkeh** [Azure/azure-documentdb-dotnet#523] opened 2018-06-13 15:09 UTC
Hi,

This defect - https://github.com/Azure/azure-docs-sdk-dotnet/issues/612 - has pretty much the only example online that i can locate on how to handle unique constraint collision.. however, it seems to behave differently depending on if you use UpsertDocumentAsync, or CreateDocumentAsync

```
try
{
    await client.UpsertDocumentAsync(uri, entity);  // 449 Retry With   -> 'Unique index constraint violation.'
    await client.CreateDocumentAsync(uri, entity);  // 409 Conflict     -> 'Unique index constraint violation.'
}
```

i am using v1.22.0 of the Microsoft.Azure.DocumentDB pkg.. is this a defect? or is there a pattern to handle this that i am missing?

**Comment by m1nkeh** [comment] 2018-06-13 15:58
This documentation seems suggest that the UpsertDocumentAsync should return 409 ...

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient.upsertdocumentasync

**Comment by mkolt** [comment] 2018-06-14 16:36
Returning 449 with unique constraint error is incorrect, and will be fixed soon. 
 
Without unique index the behavior is correct: if one transaction stats to upsert a doc which doesn’t exist (upsert->create), and another one created the doc concurrently, the upsert results in 449 (retry with/concurrency violation), so that the client would retry and on retry upsert would result in replace. With unique index the retry may not always be the solution, because another doc may be created with same unique value. For unique index, status code should be 409.
 
To work around until the fix is there, you may special-case 449 with error message that contains “Unique index constraint violation”.

**Closed by mkolt** 2018-06-14 16:36 UTC

**Comment by m1nkeh** [comment] 2018-06-14 17:07
not sure that comment constitutes closed though..

**Comment by ArtemTereshkovich** [comment] 2018-11-16 14:18
This issue is still relevant

**Comment by mkolt** [comment] 2018-11-26 23:20
Sorry for delay. The should be fixed in December, the change is in the pipeline.

**Comment by semplea** [comment] 2018-12-11 13:14
Maybe I'm missing something, but why would this throw an error at all? isn't the point of an upsert query to either insert a document, or if it already exists (based on the unique id) update the document.
This seems relevant: https://github.com/Azure/azure-docs-sdk-dotnet/issues/729#issuecomment-409355908

**Comment by m1nkeh** [comment] 2018-12-11 15:31
> Maybe I'm missing something, but why would this throw an error at all? isn't the point of an upsert query to either insert a document, or if it already exists (based on the unique id) update the document.
> This seems relevant: [Azure/azure-docs-sdk-dotnet#729 (comment)](https://github.com/Azure/azure-docs-sdk-dotnet/issues/729#issuecomment-409355908)

i raised this so long ago i can't even remember chap...  🍺

**Comment by spzSource** [comment] 2018-12-11 15:36
@semplea Upsert works as you expect in case object contains same ```id```. The issue is more about when collection has unique constraint which is differ than ```id```.

**Comment by semplea** [comment] 2018-12-11 16:20
Thanks for the explanation @spzSource, I hadn't found this explicitly anywhere in the documentation, so it's quite helpful!

**Comment by spzSource** [comment] 2018-12-11 19:46
@semplea Hmm, indeed. Now I realized that it works strange to me as well.

**Comment by semplea** [comment] 2018-12-12 08:59
Thanks for the additional explanation @spzSource! This makes more sense to me now!

**Comment by m1nkeh** [comment] 2019-02-12 16:03
So it seems like this has maybe finally been released to the production systems? Some of our error handling has suddenly snapped, and i received no update / confirmation of an impending change to the service.

Is/was this being tracked somewhere else??
