### ISSUE TITLE
Add support for DNX Core

### ISSUE THREAD

**Issue by jtbennett** [Azure/azure-documentdb-dotnet#60] opened 2015-10-08 19:06 UTC
Please add a DNX Core version of Microsoft.Azure.DocumentDB.  (If you add the code here, I'll help do the work!)

**Comment by ryancrawcour** [comment] 2015-10-09 21:11
This is something on our radar

**Comment by youngpe69** [comment] 2015-11-02 13:00
+1 For that...

**Comment by jwuliger** [comment] 2015-11-02 16:46
Yes please! +100 :+1:

**Comment by NickBrooks** [comment] 2015-11-06 12:57
+1

**Comment by ealsur** [comment] 2015-11-06 22:32
+1 Willing to help if needed

**Comment by cwiederspan** [comment] 2015-11-20 21:41
+1 and also willing to help.

**Comment by ryancrawcour** [comment] 2015-11-20 21:56
Just so I understand the ask better, is the need for this to support non windows apps .net connecting to DocumentDB? non windows .net dev (if so where is the actual app going to run)?

**Comment by cwiederspan** [comment] 2015-11-20 22:00
My interest is in building an ASP.NET 5 app that can be coded and run on a Mac with VS Code, which would require being able to run build the app on the .net core 5 platform. Would likely publish the app to Linux running on Azure.

I suppose I could just use the REST interface instead of the package, but that doesn't sound as fun!

**Comment by jwuliger** [comment] 2015-11-20 22:56
I agree with @cwiederspan. Cross-platform compatibility would be nice. I am using the current .NET SDK in a MVC 6 API App, but as we know it can only run on a windows server. 

This is also off topic a little... but a connected service (like table storage, sql etc.) for DocDB would be amazing. I know there must be some work there though!.

In my own opinion, using the rest interface directly gives me an uneasy feeling for some odd reason. You can't use all the nice magic of the API and what about layered security? I could be missing some thing though.

Anyway have a great weekend everyone.

**Comment by ryancrawcour** [comment] 2015-11-20 23:03
It's definitely something we'll be looking at, just wanted to get a sense of the reasons behind the ask. 

Running in Linux in Azure is reasonable. 
Cross plat dev on mac seems reasonable. 

It's no small undertaking to support this. We have a change a lot. There's a ton of stuff in the current library which won't work in .NET Core, do that had to be re-written. There's native code interop that has to change. 

We'll likely target net46 first and work toward dnxcore50 after.

**Comment by cwiederspan** [comment] 2015-11-20 23:33
Interesting. I had always assumed that the client library was just a nice wrapper on top of the REST calls to the back-end service using HttpClient, similar to the way that Azure Storage library works (I think). I believe that that library is now able to use .net core 5, although I haven't tried it for myself yet.

If only we could see the DocumentDB library in github ;-).

**Comment by cwiederspan** [comment] 2015-11-20 23:47
Ryan, out of curiosity, is it your crew that built the SDK for Javascript, too? Does it have feature parity with the .NET SDK? I'm wondering if we could take that JS code and rewrite it in .NET with .net core 5 "compliance"? Or am I over simplifying it?

I guess that's my way for fishing for your thoughts on what kind of gotchas might be hiding out there...?

**Comment by ryancrawcour** [comment] 2015-11-20 23:52
The .NET library has a custom written Tcp based protocol in addition to HTTP. It also has two modes of connecting, Gateway and Direct. And a few other things like a query parser etc.

The other SDKs, like Node, Java, Python etc. don't have this yet. They are just Gateway over HTTP.

**Comment by cwiederspan** [comment] 2015-11-20 23:57
Thanks - good information. That explains the native code interop dependencies. I'll take a look and see if I think I could do a good enough job to make something similar to the JS version that would work with .net core 5. Maybe get some help for your team and or other interested folks...?

**Comment by jtbennett** [comment] 2015-11-21 01:54
I'd love to help with that. Count me in.
-JB

**Comment by kpfaulkner** [comment] 2015-11-21 04:22
Hi Ryan,

Our of curiosity, of the other SDK's (Node, Python etc) is one considered
"more complete" than the others? ie, which should the community potentially
look at to see the various underlying REST calls?

Cheers

Ken

**Comment by ryancrawcour** [comment] 2015-11-21 04:31
I wouldn't say any are more complete. The node.js SDK is by far the more popular outside of the the .NET SDK.

**Comment by ryancrawcour** [comment] 2015-11-21 04:32
We're discuss this dnxcore50 support next week and make a call when we'll add support. Stay tuned.

**Comment by youngpe69** [comment] 2015-11-21 08:28
So just to add another data point - yes, the ability to build cross platform in .net would be really useful. My own workflow would be dev on Mac and deploy on Azure. I've started using ASP.NET 5 and have begun playing around with beta 8 of the storage API. Would be really cool to be able to do the same with DocumentDB as I'd have a neat stack to build on then.

See what happens when you let the cross platform genie out of the bottle? :-)

**Comment by cwiederspan** [comment] 2015-11-23 21:26
@jtbennett and anybody else interested... I've created a nearly-empty repository here - https://github.com/azure-community/azure-documentdb-dotnetcore - with a quick skeletal of an unimplemented object hierarchy based on browsing the existing SDK. That said, it's probably pretty useless in its current form, but maybe a starting point...?

Anyway, I can certainly tell you that I'm fairly new to the OSS scene, at least in terms of setting up a project from scratch, so I'm happy to handoff the repository to anybody that's got more experience in that department.

I'm also not entirely sure whether we'd be better off trying to work backwards from the existing .NET SDK, or trying to "port" the JavaScript or NodeJS SDK over to dotnetcore, so would love to get anybody's thoughts there.

**Comment by ryancrawcour** [comment] 2015-11-23 21:29
I wouldn't use the JavaScript SDK. The node.js is a better start.

**Comment by kpfaulkner** [comment] 2015-11-23 21:30
Well, given Ryan C was mentioning that MS was going to discuss if they'd do
it themselves (didn't he?). Did a decision come through?
Not sure about "porting" the NodeJS implementation, but more investigate
the requests/responses from that particular SDK.

No?

Anyway, I'm interested :)

**Comment by ryancrawcour** [comment] 2015-11-23 21:30
We're doing some tests now to see how much of the current SDK breaks on .NET Core. You might want to wait a few days until we know the extent of the changes needed. 

I'd hate this to be throw away effort.

**Comment by cwiederspan** [comment] 2015-11-23 21:56
Absolutely agree about waiting a few days or more - plenty busy without venturing down this path.

**Comment by pherbel** [comment] 2015-12-10 13:19
When will you support?

**Comment by chrizy** [comment] 2015-12-16 21:14
+1

**Comment by ryancrawcour** [comment] 2015-12-16 21:43
Sorry for delay in getting back to everyone on the thread;
We've looked at this and will hopefully be able to add support for this in Q1 2016. 
Sorry for long delay, but there's a ton of stuff already inflight that we're working on before we can get to this.

**Comment by kpfaulkner** [comment] 2015-12-16 22:12
Thanks for the update

**Comment by peterblazejewicz** [comment] 2015-12-20 18:25
:+1:

**Comment by knom** [comment] 2016-03-01 12:38
:+1:
.NET Core is key for me as well :-)

**Comment by tedvanderveen** [comment] 2016-03-01 12:55
+1

**Comment by lenardg** [comment] 2016-03-03 13:47
@ryancrawcour any updates if we are still on track for a Q1 2016 update that would support .NET Core? Thanks!

**Comment by ryancrawcour** [comment] 2016-03-03 16:09
I will update this thread once we have more info.

**Comment by ealsur** [comment] 2016-03-03 17:06
@ryancrawcour another option is if you can expose the Swagger files for the APIs, use Autorest to generate the clients :)

**Comment by ryancrawcour** [comment] 2016-03-03 17:21
thanks @ealsur . this is already in progress, however this will give you a very basic client. might be enough for some.

**Comment by jpearnshaw** [comment] 2016-03-14 16:04
+1

**Comment by sandorfr** [comment] 2016-04-13 16:25
@ryancrawcour it is apparently planned to open source the client. If it were to be done anytime soon, the community might work/help on this :).

**Comment by poteb** [comment] 2016-04-29 12:58
+1 Any update on the eta?

**Comment by timmydo** [comment] 2016-05-02 16:48
@ryancrawcour to clarify, will the result of this work make it so the nuget package can target netstandard? I'm building a dotnet cli web application using asp.net core for windows and am trying to compile against netstandard1.5, but documentdb requires me to target net46 or similar.

https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

thanks

**Comment by Bigsby** [comment] 2016-05-05 09:10
It is, indeed, that one can't implement an ASP.Net 5 Web API that uses this. Let's do this, guys.

**Comment by figox** [comment] 2016-05-14 21:06
+1

**Comment by peterblazejewicz** [comment] 2016-05-15 08:48
https://blogs.msdn.microsoft.com/webdev/2016/05/11/notes-from-the-asp-net-community-standup-may-10-2016/
https://live.asp.net/
> Question: Do we have any commitment or knowledge from Azure team as to how long after RC2 release (or RTM for that matter) will PaaS components will support it?
The Azure team is working with the ASP.NET Core team, and this should be ready very soon after each release.  Scott suggested that the two of them record the upgrade process for a web application as a demo.

**Comment by OnTheMike** [comment] 2016-05-31 07:21
Any progress on this issue? Having some issues with RC1 which are resolved in RC2, but can't upgrade due to dependency on DocumentDB.

**Comment by pherbel** [comment] 2016-06-03 05:33
any update?

**Comment by tallichet** [comment] 2016-06-13 15:41
any update? now that Q1 and almost Q2 reached the end...

**Comment by tedvanderveen** [comment] 2016-06-13 16:27
+1

**Comment by sunneh** [comment] 2016-06-13 20:04
+1

**Comment by tverboon** [comment] 2016-06-14 05:54
At some point I need to make a decision: https://jira.mongodb.org/browse/CSHARP-1177

**Comment by sandorfr** [comment] 2016-06-14 08:08
@tverboon The total lack of communication since a few monthes now and the fact that it is closed source and cloud only are really worrying me. It feels like the product is going to follow the tragic fate of SQL Azure Federations or AppFabric Caching and being discontinued. A less tragic one would be table storage, a walking dead product seeing no real improvements and having a big monolithic sdk which is a real pain.

**Comment by ryancrawcour** [comment] 2016-06-14 15:37
maybe @aliuy can comment on this.

**Comment by ealsur** [comment] 2016-06-14 16:03
@sandorfr I think that the strategy is across all Azure SDKs, not just DocumentDB. On previous versions there where dependencies on packages like Hyak that made portability impossible. It made sense to migrate to a Swagger-Autorest scenario and decorate the autogenerated client with a more friendly structure, I think that's the approach that most (if not all) the Azure SDKs are taking to be able to support Core.

**Comment by tallichet** [comment] 2016-06-14 18:27
@ryancrawcour @ealsur do you mean their is no work in progress as of today? if there is one, could you indicate a project? I'll do my best to work on it.

**Comment by ealsur** [comment] 2016-06-14 19:31
@tallichet I didn't say there is no work in progress, I said that it is probably a big change for the Azure SDKs and that they are surely working on it hand in hand with the .Net Core team, my guess is that the path might be using Swagger+Autorest (but it's a guess) and it's something being done across all Azure SDKs, not just DocumentDB.

**Comment by sunneh** [comment] 2016-06-16 18:07
@ealsur Regardless if there is a big rewrite in process for the dotnet core adjustment it takes two seconds to just the users of the SDK. The lack of communication is concerning.

**Comment by aliuy** [comment] 2016-06-17 00:36
I can confirm .NET Core support is on the DocumentDB roadmap, but there are currently no timelines as this involves quite a bit of non-trivial work.

**Comment by tverboon** [comment] 2016-06-17 05:49
@aliuy Thanks for sharing. I guess a lot of us were under the impression that .Net Core support was right around the corner. Hopefully MS will also make this library open source when you're actively porting this to .Net Core and the planned work for this is clear.

**Comment by kaleemxii** [comment] 2016-06-23 20:39
+1

**Comment by tedvanderveen** [comment] 2016-06-23 21:05
+1

**Comment by murilocurti** [comment] 2016-07-02 22:29
+1

**Comment by boades** [comment] 2016-07-03 23:31
+1 

It would be greate to have this asap.

**Comment by Radar5000** [comment] 2016-07-07 03:13
+1

asap

**Comment by weslleyhenrique** [comment] 2016-07-11 16:09
+1

**Comment by JonathanMolina** [comment] 2016-07-11 16:11
+1

**Comment by SzymonSasin** [comment] 2016-07-11 18:31
+1

**Comment by FabioReis** [comment] 2016-07-11 21:03
+1

**Comment by gabrielgio** [comment] 2016-07-11 21:03
+1

**Comment by caserzer** [comment] 2016-07-20 06:59
+1

**Comment by tedvanderveen** [comment] 2016-07-21 20:28
+1

**Comment by ChristianLegault** [comment] 2016-07-22 02:41
+1

**Comment by jj09** [comment] 2016-07-26 07:02
+1

**Comment by deman4ik** [comment] 2016-08-01 12:15
+1

**Comment by Bigsby** [comment] 2016-08-02 10:31
This should be implement as Entity Framework Core middleware.

**Comment by svickers** [comment] 2016-08-05 19:41
Holy moly surprised to see this doesn't exist already, +1

**Comment by MiddleTommy** [comment] 2016-08-10 18:18
Wouldn't it be better to have the client library be a .NET Standard library? That way it could be used from almost any platform?

**Comment by francismooreqc** [comment] 2016-08-11 17:37
+1

**Comment by sandorfr** [comment] 2016-08-11 21:37
@MiddleTommy I could not imagine they would do it another way :)

**Comment by MahmoudElShazly** [comment] 2016-08-14 21:30
+1

**Comment by tanwarsatya** [comment] 2016-08-17 15:55
unimaginable no support for the document dB,

**Comment by MoaidHathot** [comment] 2016-08-22 18:25
+1. It is really unimaginable that Microsoft Azure DocumentDB doesn't support .Net Core.

**Comment by jplindgren** [comment] 2016-08-22 21:00
+1. It is really unimaginable that Microsoft Azure DocumentDB doesn't support .Net Core.

**Comment by Vtek** [comment] 2016-08-26 14:46
+1

**Comment by lucafabbri** [comment] 2016-08-27 13:11
+1

**Comment by markglibres** [comment] 2016-08-28 12:08
+1

**Comment by Gertm** [comment] 2016-08-29 07:06
+1

**Comment by adamdriscoll** [comment] 2016-09-02 13:36
+1

**Comment by markuslindberg** [comment] 2016-09-04 05:14
+1 Looking forward to this.

**Comment by dmccaffery** [comment] 2016-09-07 19:31
Has anyone tried using MondoDB.Driver 2.3.0-rc1 along with mongodb protocol support for DocumentDB: https://azure.microsoft.com/en-us/documentation/articles/documentdb-connect-mongodb-account/

This, theoretically, will allow CoreCLR to work with Azure DocumentDB (and will also allow migration to other platforms where MongoDB is supported) -- not to mention local testing on non-Windows platforms where the Storage Emulator is not available.

Just a thought -- I'll be diving into this as a solution soon.

**Comment by dmccaffery** [comment] 2016-09-07 19:33
Also, please stop using "+1" posts... it floods peoples feeds. Use "Reactions" instead!

<img width="303" alt="screen shot 2016-09-07 at 12 33 01 pm" src="https://cloud.githubusercontent.com/assets/1803684/18325688/40dc0c78-74f7-11e6-9746-e8ba0a0e78d6.png">

**Comment by sandorfr** [comment] 2016-09-07 19:38
@dmccaffery while this is definitely a workaround, this does not provide a migration path from net451 nor supports for the new binary protocol. This is also quite experimental as well.

**Comment by dmccaffery** [comment] 2016-09-08 00:30
Agreed; definitely not meant as a long-term solution -- if you're starting from square one, though, it is an interesting alternative. Mainly because it enables migration to other services and cloud environments where MongoDb can run (hypothetically).

**Comment by MoaidHathot** [comment] 2016-09-10 18:28
Btw, I've tweeted about it to the Azure DocumentDB team and they told me they are working on it, and that they will release it before the end of the year.

**Comment by sandorfr** [comment] 2016-09-10 22:21
@MoaidHathot it was supposed to be Q1 then Q2 now before the end of the year...

**Comment by JohanOhlin** [comment] 2016-11-10 12:09
According to this recent [.NET Blog](https://blogs.msdn.microsoft.com/dotnet/2016/11/09/net-core-data-access/) post:

> The next version of the DocumentDB client library, which will be available around the Connect event, supports .NET Core.

The next [Connect event](https://connectevent.microsoft.com/) is taking place November 16-18, so it's basically around the corner :)

**Comment by henkmollema** [comment] 2016-11-16 21:01
There it is: https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core :tada:

Introducing blog post: https://azure.microsoft.com/en-us/blog/documentdb-emulator-for-local-development-and-dotnet-core-support/.

**Comment by arramac** [comment] 2016-11-18 02:07
Now available! https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core

**Closed by arramac** 2016-11-18 02:07 UTC
Labels: enhancement
