### ISSUE TITLE
DocumentClient.ReadDocumentAsync should not query across collections/databases

### ISSUE THREAD

**Issue by odegroot** [Azure/azure-documentdb-dotnet#31] opened 2015-06-30 16:34 UTC
I inadvertently constructed an inconsistent `documentLink` - the resource ID existed, but not in the db/coll that I specified - and was surprised to see that `DocumentClient.ReadDocumentAsync` happily returned the resource nonetheless.

The same goes for `DocumentClient.ReplaceDocumentAsync`, it also happily accepted my inconsistent `documentSelfLink`.

I'm using the .NET SDK NuGet package.

    <package id="Microsoft.Azure.Documents.Client" version="0.9.2-preview" targetFramework="net45" />
    or
    <package id="Microsoft.Azure.DocumentDB" version="1.1.0" targetFramework="net45" />

Here's the setup I used:

- One DocumentDB account
- Two databases within that account
- Identical schemas for the two databases: same `DocumentCollection.Id`s, same types of documents within those collections. (Different `ResourceId`s for the `DocumentCollection`s and the documents though, of course.)

Here's some code that reproduces the problem.

```c#
var endpointUrl = "https://gfms-dev.documents.azure.com:443/";
var authorizationKey = "secret";
var client = new DocumentClient(new Uri(endpointUrl), authorizationKey);

var databaseId = "GFMS-oscar";
var database = client.CreateDatabaseQuery().Where(x => x.Id == databaseId).AsEnumerable().Single();

var collectionId = "Interview";
var collection = client
	.CreateDocumentCollectionQuery(database.CollectionsLink)
	.Where(c => c.Id == collectionId)
	.AsEnumerable()
	.Single();

// A document with this resource ID exists on this account, but in a different database and collection than the ones above.
var resourceId = "RUBKAOVM1AIDAAAAAAAAAA==";
// The collection.DocumentsLink doesn't even matter, "dbs/foo/colls/bar/docs/" + resourceId works just as well.
var documentLink = collection.DocumentsLink + resourceId;
// This should fail, but it succeeds.
var response = await client.ReadDocumentAsync(documentLink);
var document = response.Resource;

// Fails: the doc-id is the same, but the db-id and col-id are not.
Assert.AreEqual(documentLink, document.SelfLink);
```

I had expected the request to fail with an exception, either because the `documentLink` is inconsistent, or because the specified resource ID does not exist in the specified collection.

I can see a use for an API that finds documents regardless of which db/collection they reside in. However, then I don't see the point of having to specify a full document self link, including database ID and collection ID. In that case, just the resource ID should be sufficient.

**Comment by ryancrawcour** [comment] 2015-06-30 16:46
You are correct. I don't believe this should be happening. I will look in to this further.

**Comment by ryancrawcour** [comment] 2015-06-30 17:31
I just noticed that you are using the very old NuGet package. You should be using the latest NuGet package - http://www.nuget.org/packages/Microsoft.Azure.DocumentDB/ 

The current version of this package is 1.1.0

Don't think this causes the behavior you are seeing, but we've definitely changed a lot since 0.9.2-preview that you appear to be using.

**Comment by odegroot** [comment] 2015-06-30 18:05
Ah, I did not see that the package `Microsoft.Azure.Documents.Client` had been deprecated and replaced by `Microsoft.Azure.DocumentDB`. Thanks for telling me! I have updated my dependencies.

The behaviour described above is also exhibited by the new package.

**Comment by ryancrawcour** [comment] 2015-06-30 19:05
suspected it would. I am looking in to this now.

**Comment by ryancrawcour** [comment] 2015-07-02 19:20
this has been confirmed as a bug, we will fix in a future release.

**Comment by odegroot** [comment] 2015-11-06 08:58
Is there any update on this?

**Comment by ryancrawcour** [comment] 2015-11-06 19:24
this has been fixed but it missed the release of 1.5.0. we are working on a 1.5.1 which would include this fix.

**Comment by ryancrawcour** [comment] 2015-11-06 19:26
btw. if you make use of the new ID Based Routing (not the resource ids and selflinks) then this problem does not exist. https://azure.microsoft.com/en-us/blog/azure-documentdb-bids-fond-farewell-to-self-links/

**Comment by odegroot** [comment] 2015-11-24 15:24
Any update on this? 1.5.1 is out now, but it doesn't include a fix for this issue. Yes I've tested it.

**Comment by ryancrawcour** [comment] 2015-11-24 21:10
i'd have to follow up on this, this should've been a backend fix.

**Comment by odegroot** [comment] 2015-11-26 12:15
Yes please. What does *'should've been a backend fix'* mean?

**Comment by ryancrawcour** [comment] 2015-11-30 23:08
it means that it should be fixed by a backend update and not an SDK update.

**Closed** 2016-06-14 00:31 UTC
Labels: pending verification
