### ISSUE TITLE
Invalid length for a Base-64 char array or string

### ISSUE THREAD

**Issue by ArjunMenonUK** [Azure/azure-documentdb-dotnet#196] opened 2017-01-24 06:56 UTC
Hi,

I have been using Microsoft.Azure.DocumentDB dll version 1.8.0 till yesterday and i updated to 1.11.1 today and after that CreateDocumentQuery method has been throwing error "**Partition routing information cannot be extracted from the query when running in a 32-bit process**" , also i have been using the DocumentDB build in API to calculate the distance from a position using Lat-Long and it also has stopped working throwing error **" Invalid length for a Base-64 char array or string"** . If i revert back to 1.8.0 all seems to be working. The values i passed as lat-long is **37.7908584075998,-122.406202554703** 

What could be the issue?

**Comment by rnagpal** [comment] 2017-01-24 07:04
@ArjunMenonUK First issue will be fixed very soon and we will release it this week. As a workaround, you need to make the your host process as 64 bit. Can you tell me what type of application is that so that I can suggest you the appropriate workaround?

We will look into the second issue. cc:@arramac for the Geospatial issue.

**Comment by ArjunMenonUK** [comment] 2017-01-24 07:07
@rnagpal , its a WEB API service , which is hosted in Azure itself.

**Comment by rnagpal** [comment] 2017-01-24 07:14
@ArjunMenonUK Can you set the Platform for the Web API service as 64-bit under Settings through Azure portal?

**Comment by ArjunMenonUK** [comment] 2017-01-24 07:28
@rnagpal  i will try and will let you know

**Comment by ArjunMenonUK** [comment] 2017-01-24 07:34
@rnagpal  hi, i changed  it and published my code and still that Distance Calculation service is throwing error

> **Invalid length for a Base-64 char array or string. .Stack Trace :    at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)**

**Comment by ArjunMenonUK** [comment] 2017-01-24 16:31
Hi @rnagpal  any update on this?

**Comment by rnagpal** [comment] 2017-01-24 23:27
@ArjunMenonUK can you paste the code for the lat-long issue?

**Comment by rnagpal** [comment] 2017-01-25 14:26
@arramac will help you resolving the lat-long issue once you send us the code.

**Comment by rnagpal** [comment] 2017-01-27 15:02
@ArjunMenonUK  The 32 bit related issue that you faced is fixed in 1.11.3 version now, so you don't have to use x64 as the Platform though it's recommended for better performance that x86.

**Comment by arramac** [comment] 2017-01-27 22:04
Fixed now

**Comment by rnagpal** [comment] 2017-01-28 07:29
@ArjunMenonUK Once you send us the sample code for the lat-long issue @arramac can help you fix that issue at well.

**Comment by rnagpal** [comment] 2017-01-28 07:33
Reopening by updating the title.

**Comment by ArjunMenonUK** [comment] 2017-01-28 07:40
I am on leave till next Tuesday. Will do once I reach back. Thanks a lot for the quick response

**Comment by ArjunMenonUK** [comment] 2017-01-31 05:15
Hi @rnagpal 
`string DistanceQuery="SELECT ST_DISTANCE( {{ 'type': 'Point', 'coordinates':[{0},{1}]}},{{'type': 'Point', 'coordinates':[{2}, {3}]}}) AS Distance"`

`client.CreateDocumentQuery(link, string.Format(DistanceQuery, longitude, latitude, zurLong, zurLatitude)).AsEnumerable().FirstOrDefault();`

this is the query we are executing to get the distance between two lat-long.

**Comment by zfang** [comment] 2017-02-03 00:49
I cannot reproduce your issue with that code snippet on v1.11.1 (or later versions). Could you paste the full call stack of your Exception?

**Comment by ArjunMenonUK** [comment] 2017-02-03 05:28
@zfang  
`public decimal ComputeDistancefromCityCentre(string latitude, string longitude, string endpointuri, string primarykey, string documentName, string collectionName)
        {
            decimal computedDistance = 0;

            decimal baseLongitude=<base location longitude>;
            decimal baseLatitude =<base location latitude>;
            using (var client = new DocumentClient(new Uri(endpointuri),
                    primarykey))
            {
                string link = GetCollectionDetails(client, documentName, collectionName);
                var distance = client.CreateDocumentQuery(link, string.Format(AzureConstant.DistanceQuery, longitude, latitude, baseLongitude, baseLatitude )).AsEnumerable().FirstOrDefault();
                var distanceValue = JsonConvert.DeserializeObject<dynamic>(distance.ToString());
                computedDistance = (((JObject)distanceValue).Count > 0) ? distanceValue.Distance / 1000 : 0;
                return computedDistance;
            }
        }`

**Comment by zfang** [comment] 2017-02-03 09:04
Sorry I meant the stack trace of your exception. Did exception happen at CreateDocumentQuery?

On a separate note, you can simplify things by just doing "SELECT VALUE ..." which will give you double. The ToString and DeserializeObject in your example is also unnecessary because we already return you a dynamic object, which is pretty much a JObject.

**Comment by ArjunMenonUK** [comment] 2017-02-04 07:01
Hi @zfang ,

I tried the distance in a console application using 1.11.1 and there seems to be no issue, apologies for the wrong ticket. One query , what do you mean by "SELECT VALUE "?

**Comment by zfang** [comment] 2017-02-04 07:35
I mean "SELECT VALUE ST_DISTANCE( {{ 'type': 'Point', 'coordinates':[{0},{1}]}},{{'type': 'Point', 'coordinates':[{2}, {3}]}})" will give you a JValue that is either a number or null (which means undefined).

**Comment by ArjunMenonUK** [comment] 2017-02-04 07:36
@zfang ,

thanks a lot :+1:

**Closed** 2017-02-04 07:36 UTC
Labels: investigating

**Comment by zfang** [comment] 2017-02-04 08:30
It would be possible to get undefined (or null, in your case) if your GeoJSON is invalid (e.g. lat/long is out of range).
