### ISSUE TITLE
ASP.NET Core project failing to load a DocumentDB dll when targeting full netfx

### ISSUE THREAD

**Issue by rswillis** [Azure/azure-documentdb-dotnet#137] opened 2016-07-18 21:32 UTC
I'm porting over some services and noticed that this library had not been updated to dotnet core

"Package Microsoft.Azure.DocumentDB 1.8.0 is not compatible with netcoreapp1.0"

Any thoughts as to when this might be updated or some alternative method of working with DocumentDb in code might be suggested?

thx for the work on this. I have found it really invaluable.

**Comment by GmsDave** [comment] 2016-07-25 18:39
Any updates on this? I'm just about to create new project and was hoping to use .NET Core and DocumentDB and Azure Table Storage, however, when I installed those packages, I got the following:
![untitled](https://cloud.githubusercontent.com/assets/18301427/17112784/c4bf11ee-5264-11e6-96c2-8617cc7491d8.png)

**Comment by mimig1** [comment] 2016-07-26 17:40
At this time, .NET Core is not supported. We are tracking Core support on this User Voice item: https://feedback.azure.com/forums/263030-documentdb/suggestions/12287628--net-core-support and we'll keep it updated as time goes on.

**Comment by iryanzhang** [comment] 2016-08-17 10:59
I know DocumentDB doesn't support .NET Core, but how about ASP.NET Core (ASP.NET 5) 
There is no compatible issue throw out when I get the nuget and compile successfully,
But there is run time issue

System.DllNotFoundException: Unable to load DLL &#x27;Microsoft.Azure.Documents.ServiceInterop.dll&#x27;: The specified module could not be found.

**Comment by mingaliu** [comment] 2016-08-17 21:04
The possible cause for loading "load DLL 'Microsoft.Azure.Documents.ServiceInterop.dll'" is in detail here
https://github.com/Azure/azure-documentdb-dotnet/issues/140
The .NET Core work is planned, the goal is to deliver by the end of 2016.

**Comment by iryanzhang** [comment] 2016-08-18 10:49
I don't think it's X64 or X86 cause this issue. Because no matter which platform I choose, it always occur.
Per my understanding,  ASP.NET Core is different concept with .NET Core. It can be based on .Net.Core or .Net Framework. It seems even I choose .Net framework it's still incompatible with Azure DocumentDB.
Finally,  after I switch to  WebAPI 2.0 project and the issue is gone. 

If it is the case and as ASP.NET 5 (ASP.NET CORE) has been released for a period time and being highly recommended,  we should highlight it can't work with some Azure SDK like Document DB

**Comment by arramac** [comment] 2016-11-18 02:07
Now available! https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core

**Comment by rnagpal** [comment] 2016-11-21 04:54
@iryanzhang I'll look into the issue of using DocumentDB with ASP.NET Core project when targeting full .net framework(net451 or above)

**Comment by rnagpal** [comment] 2016-11-22 04:44
Reopening after updating the title with the issue that @iryanzhang mentioned

**Comment by rnagpal** [comment] 2016-12-09 21:46
@iryanzhang Please try this with the new release 1.11.0 That should work with ASP.NET Core project template targeting full .NET Framework. Let me know if that works.

**Comment by rnagpal** [comment] 2017-01-29 00:44
This should be fixed now with 1.11.* release of the SDK

**Closed by rnagpal** 2017-01-29 00:44 UTC

**Comment by paval-tech** [comment] 2017-03-19 07:27
I have the same issue. SDK version is 1.12.
ASP.NET Core project failing to load a DocumentDB dll when targeting full framework.

`System.DllNotFoundException: Unable to load DLL 'Microsoft.Azure.Documents.ServiceInterop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Azure.Documents.ServiceInteropWrapper.CreateServiceProvider(String configJsonString, IntPtr& serviceProvider)
   at Microsoft.Azure.Documents.Query.QueryPartitionProvider.Initialize()
   at Microsoft.Azure.Documents.Query.QueryPartitionProvider.GetPartitionedQueryExecutionInfoInternal(SqlQuerySpec querySpec, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, Boolean isContinuationExpected)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.<GetPartitionedQueryExecutionInfoAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextFactory.<CreateDocumentQueryExecutionContextAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<CreateDocumentQueryExecutionContextAsync>d__12.MoveNext()`
